# application.properties

# Defines the maximum number of connections in the pool
# Set based on your expected concurrency. Default is usually 100.
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.client.uri=${spring.data.mongodb.uri}
spring.data.mongodb.client.min-connections-per-host=5
spring.data.mongodb.client.max-connections-per-host=50